baseURL       = "https://itaygueta.com/"
languageCode  = "en-us"
title         = "Itay Gueta"
theme        = "ananke"
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.renderer]
      unsafe = true
